name: deploy vue application
permissions:
  contents: write
  pull-requests: read

on:
  pull_request:
  push:
   branches:
   - master

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - name: Build application
      run: npm run build
